// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

#nullable disable

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    [Migration("20230329214742_Reviews")]
    partial class Reviews
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelApi.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            City = "Mexico City",
                            Country = "Mexico"
                        },
                        new
                        {
                            DestinationId = 2,
                            City = "Paris",
                            Country = "France"
                        },
                        new
                        {
                            DestinationId = 3,
                            City = "New York",
                            Country = "United States"
                        },
                        new
                        {
                            DestinationId = 4,
                            City = "Tokyo",
                            Country = "Japan"
                        },
                        new
                        {
                            DestinationId = 5,
                            City = "Perth",
                            Country = "Australia"
                        });
                });

            modelBuilder.Entity("TravelApi.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("ReviewId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Description = "Words Would go here",
                            DestinationId = 1,
                            Title = "Mexico Review"
                        },
                        new
                        {
                            ReviewId = 2,
                            Description = "Words Would go here",
                            DestinationId = 2,
                            Title = "France Review"
                        },
                        new
                        {
                            ReviewId = 3,
                            Description = "Words Would go here",
                            DestinationId = 3,
                            Title = "United States Review"
                        },
                        new
                        {
                            ReviewId = 4,
                            Description = "Words Would go here",
                            DestinationId = 4,
                            Title = "Japan Review"
                        },
                        new
                        {
                            ReviewId = 5,
                            Description = "Words Would go here",
                            DestinationId = 5,
                            Title = "Australia Review"
                        });
                });

            modelBuilder.Entity("TravelApi.Models.Review", b =>
                {
                    b.HasOne("TravelApi.Models.Destination", null)
                        .WithMany("Reviews")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelApi.Models.Destination", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
